import { Inter } from 'next/font/google'
import './globals.css'
import { StyledEngineProvider } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aquarium Parameter Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="root">
      <body className={inter.className}>
        <StyledEngineProvider>
            {children}
        </StyledEngineProvider>
      </body>
    </html>
  )
}
